#!/bin/sh
find /var/www/html -not -path "/var/www/html/wp-content/*" -exec chown -R 33:88 {} \; && find /var/www/html  -type f -not -path "./var/www/html/wp-content/*" -exec chmod 664 {} \; && find /var/www/html -not -path "/var/www/html/wp-content/*" -type d -exec chmod 775 {} \;
