#!/bin/sh
find /var/www/html -not -path "./wp-content/*" -exec chown -R nobody:www-data {} \; && find /var/www/html  -type f -not -path "./wp-content/*" -exec chmod 664 {} \; && find /var/www/html -not -path "./wp-content/*" -type d -exec chmod 775 {} \;
